### ISSUE TITLE
LeNet growing raising error after seconf itera

### ISSUE THREAD

**Issue by AmanGoyal99** [SuReLI/NeurOps#1]
While growing LeNet for just second iteration, this error terminates the program.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/51092051/216535522-e2dc134e-decb-48d7-a3e7-3001528ba1f5.png">

I think earlier version did not produce this error for LeNet.

**Comment by k8lion** [comment]
Fixed with the latest [commit](https://github.com/SuReLI/NeurOps/commit/00077ef8a4d8b96bd5b409aaa8678416e15e3d1f)]

**Comment by k8lion** [comment]
Fixed with the latest [commit](https://github.com/SuReLI/NeurOps/commit/00077ef8a4d8b96bd5b409aaa8678416e15e3d1f).
